//Auto-generated by OpenFD
#ifndef KERNEL_H
#define KERNEL_H
#define BP_LEFT 4
#define BP_RIGHT 5
#define INCL_BND_PTS 0
void diff_right(float *v, float *vh, const float *u, const float *uh, const float hi, const int n);
void diff_left(float *v, float *vh, const float *u, const float *uh, const float hi, const int n);
void diff_interior(float *v, float *vh, const float *u, const float *uh, const float hi, const int n);
void interp_right(float *v, float *vh, const float *u, const float *uh, const int n);
void interp_left(float *v, float *vh, const float *u, const float *uh, const int n);
void interp_interior(float *v, float *vh, const float *u, const float *uh, const int n);
#endif //KERNEL_H
